############################
## CHANGE THESE
############################

baseURL: 'https://%USER%.github.io/%NAME%'
title: %NAME%

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


